/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mvdr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d92b4dc43dea6ec1a38948dbc0bcd270)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mvdr_test/mvdr.h>
// pydoc.h is automatically generated in the build directory
#include <mvdr_pydoc.h>

void bind_mvdr(py::module& m)
{

    using mvdr    = ::gr::mvdr_test::mvdr;


    py::class_<mvdr, gr::block, gr::basic_block,
        std::shared_ptr<mvdr>>(m, "mvdr", D(mvdr))

        .def(py::init(&mvdr::make),
           py::arg("num_inputs"),
           py::arg("sampling_frequency"),
           py::arg("taps"),
           py::arg("target_prn"),
           py::arg("ms_to_process"),
           D(mvdr,make)
        )
        



        ;




}








